#!/usr/bin/env bash
set -e

# give jenkins its own home and TMPDIR, accessible from uid 1000 as is used inside the jenkins docker
sudo mkdir -p /var/jenkins_home/TMPDIR
sudo chown -R 1000 /var/jenkins_home

# allow jenkins to fire up ephemeral containers (TODO: create local jenkins user if no user at uid 1000 exists)
sudo usermod -aG docker $(getent passwd 1000 | cut -d: -f1)

docker build \
    -t jenkins:local \
    -f Dockerfile \
    .
