#!/usr/bin/env bash
set -euo pipefail;IFS=$'\t\n'

cd "$(dirname "${0}")"

docker build \
    --tag "hugojosefson/jenkins-dockerception:lts" \
    .


if [[ "${1:-""}" == "--push" ]]; then
  docker push "hugojosefson/jenkins-dockerception:lts"
fi
